import { IMessage } from "../components/Message";

const baseURL = "https://linguabot-pc.alexkreidler.com";

// Generated by https://quicktype.io

export interface MessageResponse {
  id: string;
  history: History[];
}

export interface History {
  id: string;
  input_orig: string;
  input_en: string;
  result_en: string;
  result_lang: string;
  time_received: string;
}

/** Sends a chat message */
export const sendMessage = async (
  msg: string,
  chatID: string,
  lang: string
): Promise<IMessage> => {
  const msgURL = `${baseURL}/chats/${chatID}/message?lang=${lang}`;
  const raw = await fetch(msgURL, {
    method: "POST",

    body: JSON.stringify({
      // message: {
      text: msg,
      // }
    }),
    
    headers: {
      "content-type": "application/json",
    },
  });
  console.log(msgURL, raw);

  const res: MessageResponse = await raw.json();

  console.log("msg res", res);
  
  const r = res.history?.reverse()[0];

  return {
    //   _id: r.id,
    text: r.result_lang,
    date: new Date(r.time_received),
    // system: true,
    sender: "Linguachat",
  };
  // console.log();
  // return res.history[0]
};
